[View in Colaboratory](https://colab.research.google.com/github/thayumaanavan/Deep-Reinforcement-Learning/blob/master/Q_Learning.ipynb)

In [2]:
!pip install gym
import numpy as np
import gym
import random

    100% |████████████████████████████████| 1.5MB 9.4MB/s 
    100% |████████████████████████████████| 1.0MB 17.7MB/s 
  Running setup.py bdist_wheel for gym ... - \ | / done
  Stored in directory: /content/.cache/pip/wheels/cb/14/71/f4ab006b1e6ff75c2b54985c2f98d0644fffe9c1dddc670925
Successfully built gym


In [0]:
#Create the environment
env = gym.make("FrozenLake-v0")

In [8]:
# Create Q table and initialize it

action_size = env.action_space.n
state_size = env.observation_space.n

qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [0]:
# Create the hyperparameters
total_episodes = 10000
learning_rate = 0.8
max_steps = 99
gamma = 0.95

#exploration paramters
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.01

In [20]:
# Q learning algo
rewards =[]

for episode in range(total_episodes):
  
  state = env.reset()
  done = False
  step =0
  total_rewards = 0
  
  for step in range(max_steps):
    
    exp_exp_tradeoff = random.uniform(0,1)
    
    if exp_exp_tradeoff >epsilon:
      action = np.argmax(qtable[state,:])
    else:
      action = env.action_space.sample()
      
    new_state, reward, done, info = env.step(action)
    
    qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state,:]) -qtable[state, action]) 
    
    total_rewards += reward
    
    state = new_state
    
    if done == True:
      break
  
  episode += 1
  epsilon = min_epsilon + (max_epsilon - min_epsilon)* np.exp(-decay_rate * episode)
  rewards.append(total_rewards)
  
print("score over time:" + str(sum(rewards)/total_episodes)) 
print(qtable) 

score over time:0.493
[[2.59336950e-01 4.28550706e-02 4.27602045e-02 7.18496508e-02]
 [5.01935555e-05 4.88405325e-03 2.41682260e-02 1.64258900e-01]
 [1.37183777e-01 1.07668618e-02 3.41482001e-02 3.73490250e-02]
 [2.28287784e-04 1.22761884e-03 9.32098869e-03 4.18543624e-02]
 [3.01640007e-01 2.46374332e-03 6.42967767e-03 1.91794148e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.90637986e-02 2.82943759e-07 4.94269893e-06 4.20122019e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.51431244e-01 2.05733811e-02 1.90891380e-02 4.44309241e-01]
 [1.49614972e-04 3.82845061e-01 1.75166565e-01 5.40073424e-03]
 [6.42535764e-01 5.78972457e-03 6.31816782e-03 2.06678664e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.69511742e-02 6.28674239e-04 4.90087845e-01 5.87312090e-02]
 [3.08730653e-01 9.48822234e-01 3.23433630e-01 9.33626145e-02]
 [0.00000000e+00 0.00000000e+00 0

In [21]:
env.reset()

for episode in range(5):
  state = env.reset()
  step =0
  done = False
  print("****************************************************")
  print("EPISODE"+ str(episode))
  
  for step in range(max_steps):
    env.render()
    action = np.argmax(qtable[state,:])
    
    new_state, reward, done, info = env.step(action)
    
    if done:
      break
    state = new_state
env.close()

****************************************************
EPISODE0

SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Left)
SFFF
FHFH
FFFH
HFFG
  (Up)
SFFF
FHFH
FFFH
